# Generated by Django 6.0.5 on 2026-05-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_he', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('university', 'אוניברסיטה'), ('mechlala', 'מכללה'), ('mechlala_academic', 'מכללה אקדמית')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'מוסד',
                'verbose_name_plural': 'מוסדות',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name_he', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='institutions.institution')),
            ],
            options={
                'verbose_name': 'פקולטה',
                'verbose_name_plural': 'פקולטות',
                'constraints': [models.UniqueConstraint(fields=('institution', 'slug'), name='unique_faculty_institution_slug')],
            },
        ),
    ]
