FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

RUN pip install uv

COPY scrapers/pyproject.toml ./scrapers/pyproject.toml
RUN cd scrapers && uv pip install --system -e .

RUN playwright install chromium

COPY scrapers/ ./scrapers/
COPY .env .env
