# Generated by Django 6.0.5 on 2026-05-09 16:19

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewanalysis',
            name='embedding',
        ),
        migrations.AddField(
            model_name='reviewanalysis',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
