# Generated by Django 6.0.5 on 2026-05-09 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('psychometric_score', models.IntegerField(blank=True, null=True)),
                ('bagrut_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('source_page', models.URLField(blank=True)),
                ('utm_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='programs.program')),
            ],
            options={
                'verbose_name': 'ליד',
                'verbose_name_plural': 'לידים',
                'indexes': [models.Index(fields=['status', 'created_at'], name='leads_lead_status_2b0e1e_idx')],
            },
        ),
    ]
